name: Upstream Preview

on:
  repository_dispatch:
    types: [trigger-upstream-preview]
  workflow_dispatch:
    inputs:
      commit_hash:
        description: "Commit hash from MaterialKolor"
        required: true
      pr_number:
        description: "PR number (if applicable)"
        required: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Update submodule
        run: |
          git submodule update --init --recursive
          cd library
          git fetch origin ${{ github.event.client_payload.commit_hash || github.event.inputs.commit_hash }}
          git checkout ${{ github.event.client_payload.commit_hash || github.event.inputs.commit_hash }}

      - name: setup-java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: adopt

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v3

      - name: Build web app
        run: ./gradlew wasmJsBrowserDistribution

      - name: Set Channel ID
        run: |
          if [ -n "${{ github.event.client_payload.pr_number || github.event.inputs.pr_number }}" ]; then
            echo "CHANNEL_ID=upstream-pr-${{ github.event.client_payload.pr_number || github.event.inputs.pr_number }}" >> $GITHUB_ENV
          else
            echo "CHANNEL_ID=upstream-${{ github.event.client_payload.commit_hash || github.event.inputs.commit_hash }}" >> $GITHUB_ENV
          fi

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JORDOND_A4B2F }}
          projectId: jordond-a4b2f
          channelId: ${{ env.CHANNEL_ID }}
